import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")

VIP_GROUP_ID = int(os.getenv("VIP_GROUP_ID"))
MONTHLY_PRICE_USD = 10
